### ISSUE TITLE
Getting Exception Error while running the program

### ISSUE THREAD

**Issue by anushanair20** [EricZimmerman/AmcacheParser#1]
I am getting the following Exception while running the amcache parser in windows 10
"An unhandled exception of type 'System.NotSupportedException' occurred in FluentCommandLineParser.dll".Can you please help me with this.

![untitled](https://cloud.githubusercontent.com/assets/17286399/14072174/ed00d4ea-f4da-11e5-84e6-7074db8b4f20.png)

**Comment by EricZimmerman** [comment]
this is a command line app, so i assume you provided one.

what command line did you use?

i do see some indication of what the issue is in the lower left corner about Option f

**Comment by EricZimmerman** [comment]
Closing due to lack of response.
