### ISSUE TITLE
SHA1 hashes for Driver Binaries

### ISSUE THREAD

**Issue by chadtilbury** [EricZimmerman/AmcacheParser#14]
In the InventoryDriverBinary keys the DriverID values are typically the SHA1 hash of the driver (with two null bytes prepended).  Would it be possible to either strip those first two bytes from the data presented in the CSV output or create a new column for the SHA1 hash (with the bytes stripped)?  This would make it easier to grab those values out of the output for checks against known good/known bad hash databases.

**Comment by EricZimmerman** [comment]
yea ill strip them like i do the others.

**Comment by EricZimmerman** [comment]
this is done
