### ISSUE TITLE
Request: Output dates in more internationally recognised format

### ISSUE THREAD

**Issue by bridgeythegeek** [EricZimmerman/AmcacheParser#2]
Not an issue, more a request.

AmcacheParser currently outputs dates in `MM-dd-yyyy HH:mm:ss` format, as defined in `FECacheOutputMap` (https://github.com/EricZimmerman/AmcacheParser/blob/master/AmcacheParser/Program.cs#L351) and `PECacheOutputMap` (https://github.com/EricZimmerman/AmcacheParser/blob/master/AmcacheParser/Program.cs#L381).

When loading the TSV output into a tool such as Excel, Excel fails to recognise some of the dates correctly because it's expecting them to be in my (UK) locale, i.e. `dd-MM-yyyy HH:mm:ss`.

I appreciate that changing the code to detect the correct locale for the user might be a pain, but I'd suggest that a format of `yyyy-MM-dd HH:mm:ss` might be more universally accepted by tools reading the TSV.

**Comment by EricZimmerman** [comment]
OK this is done. changes as follows:

Added --mp and --dt switches for more precise timestamps and custom date time format

new default timestamp format is:

yyyy-MM-dd HH:mm:ss K

which can be overridden via --dt or changed to

yyyy-MM-dd HH:mm:ss.fffffff K

by using --mp

This matches options in other programs like LECmd, PECmd, etc and gives people a choice for what they want to see along with a sane default

you could for example use --dt "G" for your locale's default settings

https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx

I just pushed the update, so please give it a whirl and thanks for the feedback
