### ISSUE TITLE
AmcacheParser fails to parse certain older version Amcache hives which contain the Root\InventoryApplication key

### ISSUE THREAD

**Issue by geoffblack** [EricZimmerman/AmcacheParser#4]
In a Windows 10 image release 1511, build 10586, the Amcache hive contains the `Root\InventoryApplication` key which you use to determine whether it is the "old" or "new" format, but it is not, in fact, the "new" format. (The `Root\InventoryApplication` in this hive contains only the `ProviderSyncId` value and _no_ child keys). AmcacheParser fails to parse it, thinking that it's the new format:

```
Hive does not contain a InventoryApplicationFile and/or InventoryApplication key. Processing cannot continue
Hive did not contain program entries nor file entries.
```

**Comment by EricZimmerman** [comment]
Fixed in v1.0.0.1 being released today. Many thanks for the report. I changed it to look for the "Root\InventoryApplicationFile" key as this is more specific to the new format
