### ISSUE TITLE
"There was an error: sequence contains no elements"

### ISSUE THREAD

**Issue by 7MinSec** [EricZimmerman/AmcacheParser#7]
Hi there,

I got this error when running the util on an Amcache.hve extracted off a dead box.  Other utilities, such as RegRipper seem to have no problem.  Any thoughts on what might be going on?

Brian

**Comment by EricZimmerman** [comment]
can you send me the hive? what version of the tool are you using?

other tools don't do nearly the same thing as my parts are done so comparing them like that doesn't help too much. 

you can also run the debug and trace and see if you get any more context. does it say whether or not it's a newer and old format?

**Comment by 7MinSec** [comment]
Hi Eric,

Sorry, I certainly didn't mean to sound critical of your tool.  I was just noting that I tried another parser on the file just as a sanity check to make sure I didn't have a jacked hive.

I don't think I can send the hive as this is part of an active incident.  This is the screenshot I took at the time:

![amcache](https://user-images.githubusercontent.com/17596787/55034762-44633180-4fe4-11e9-8cbe-640517c8cd68.png)

I will try the debug/trace options when I get back to the box and send more info.

Thanks,
Brian

**Comment by EricZimmerman** [comment]
oh no worries, i was just saying being able to parse a hive, or a few keys in a hive, wont reveal the issue here.

shoot me email and let's see if we can arrange the data. my only goal is to fix the issue.

also, confirm you are using v1.3.2.0 please

**Comment by 7MinSec** [comment]
Will shoot you an email, thx.

**Comment by EricZimmerman** [comment]
closing since our test worked
