### ISSUE TITLE
Fails to parse the following hive

### ISSUE THREAD

**Issue by evandrix** [EricZimmerman/AmcacheParser#8]
Parsing the following files
[Pooh.hve](https://anonfiles.com/5bgdr4x5n5/Pooh_hve)
[Pooh.hve.LOG1](https://anonfiles.com/4fgdr6xfna/Pooh.hve_LOG1)

via `AmcacheParser.exe -f "\full\win\path\to\Pooh.hve" --csv "\full\win\path\to\current\folder"`

produces:
```
AmcacheParser version 1.3.3.0

Author: Eric Zimmerman (saericzimmerman@gmail.com)
https://github.com/EricZimmerman/AmcacheParser

Command line: -f Pooh.hve --csv .

Hive does not contain a File and/or Programs key. Processing cannot continue
Hive did not contain program entries nor file entries. Exiting
```

**Comment by EricZimmerman** [comment]
It parser it fine. Read the message. The proper keys were not found. 

That's because it's not an amcache hive.
