### ISSUE TITLE
AmcacheParser buffer too small

### ISSUE THREAD

**Issue by jrobm2k9** [EricZimmerman/AmcacheParser#9]
Hi Eric, 

I ran the AmcacheParser and got the error attached in the Screenshot, unfortunately I can't copy/zip the amcahe.hve and send it to you because the file is in use, is there any info I can give you to help fix the error, or do you know how to stop it so that I can send it to you?

![amcache buffer](https://user-images.githubusercontent.com/16310787/68618448-f32e8200-048e-11ea-8b3a-e3b4e8b7f871.PNG)

**Comment by EricZimmerman** [comment]
you can use KAPE to pull the locked file, then send it, but that error looks to be related to it doing a raw read, vs a parsing issue. if kape didnt work youd have to use something else that can get around a file being locked, like x-ways

**Comment by jrobm2k9** [comment]
Ok, thanks, I'll try that.  Do you still want me to send it to the email listed in the error?

**Comment by EricZimmerman** [comment]
Yes please

**Comment by jrobm2k9** [comment]
will do, thanks!
